In [2]:
# пустой кортеж:
()

()

In [4]:
# кортеж из элементов типа String:
favoritelang = ("Python", "Julia", "R")

("Python", "Julia", "R")

In [6]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [8]:
# кортеж из элементов разных типов:
x2 = (1, 0.2, "tmp")

(1, 0.2, "tmp")

In [10]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [12]:
# длина кортежа x2:
length(x2)

3

In [14]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 0.2, "tmp")

In [16]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
c = x1[2] + x1[3]

5

In [18]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [20]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

In [22]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")


Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [24]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [26]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [28]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [30]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [32]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [34]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [36]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b, a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [38]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [40]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [42]:
# проверка эквивалентности двух множеств:
S1 = Set([1, 2]);
S2 = Set([3, 4]);
issetequal(S1, S2)

false

In [44]:
S3 = Set([1, 2, 2, 3, 1, 2, 3, 2, 1]);
S4 = Set([2, 3, 1]);
issetequal(S3, S4)

true

In [46]:
# объединение множеств:
C=union(S1, S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [48]:
# пересечение множеств:
D = intersect(S1, S3)

Set{Int64} with 2 elements:
  2
  1

In [50]:
# разность множеств:
E = setdiff(S3, S1)

Set{Int64} with 1 element:
  3

In [52]:
# проверка вхождения элементов одного множества в другое:
issubset(S1, S4)

true

In [54]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [56]:
# удаление последнего элемента множества:
pop!(S4)

2

In [58]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [60]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]
empty_array_3 = (Float64)[]

Float64[]

In [62]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [64]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [66]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [82]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.538198  0.151628  0.349995  0.891214  …  0.272525  0.551418  0.792748

In [86]:
c = rand(2,3)

2×3 Matrix{Float64}:
 0.736888  0.554953  0.54472
 0.345794  0.439748  0.0839246

In [90]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.900014  0.459259  0.15483
 0.369843  0.55291   0.378339
 0.563482  0.104964  0.956263
 0.63803   0.029654  0.776925

[:, :, 2] =
 0.839086   0.103351   0.168964
 0.91003    0.198215   0.950964
 0.444656   0.0881609  0.544898
 0.0677078  0.391478   0.0908424

In [92]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [94]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [98]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [100]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [102]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [104]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [106]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5, (3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [108]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [110]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a, (2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [112]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [114]:
# транспонирование
c = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [116]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 19  19  19  11  15
 15  10  19  18  19
 20  13  16  10  15
 12  11  14  18  13
 12  12  10  10  20
 17  17  16  10  11
 18  10  19  10  20
 13  17  13  20  12
 18  11  12  17  14
 20  16  15  18  16

In [118]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 19
 10
 13
 11
 12
 17
 10
 17
 11
 16

In [120]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 19  15
 10  19
 13  15
 11  13
 12  20
 17  11
 10  20
 17  12
 11  14
 16  16

In [122]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 19  19  11
 10  19  18
 13  16  10
 11  14  18
 12  10  10
 17  16  10
 10  19  10
 17  13  20
 11  12  17
 16  15  18

In [124]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 15  19
 12  13
 17  11

In [126]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 19
 11
 15

In [128]:
# сортировка по столбцам:
sort(ar, dims=1)

10×5 Matrix{Int64}:
 12  10  10  10  11
 12  10  12  10  12
 13  11  13  10  13
 15  11  14  10  14
 17  12  15  11  15
 18  13  16  17  15
 18  16  16  18  16
 19  17  19  18  19
 20  17  19  18  20
 20  19  19  20  20

In [130]:
# сортировка по строкам:
sort(ar, dims=2)

10×5 Matrix{Int64}:
 11  15  19  19  19
 10  15  18  19  19
 10  13  15  16  20
 11  12  13  14  18
 10  10  12  12  20
 10  11  16  17  17
 10  10  18  19  20
 12  13  13  17  20
 11  12  14  17  18
 15  16  16  18  20

In [132]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 1  1  1  0  1
 1  0  1  1  1
 1  0  1  0  1
 0  0  0  1  0
 0  0  0  0  1
 1  1  1  0  0
 1  0  1  0  1
 0  1  0  1  0
 1  0  0  1  0
 1  1  1  1  1

In [134]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

28-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(6, 1)
 CartesianIndex(7, 1)
 CartesianIndex(9, 1)
 CartesianIndex(10, 1)
 CartesianIndex(1, 2)
 CartesianIndex(6, 2)
 CartesianIndex(8, 2)
 CartesianIndex(10, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 ⋮
 CartesianIndex(10, 3)
 CartesianIndex(2, 4)
 CartesianIndex(4, 4)
 CartesianIndex(8, 4)
 CartesianIndex(9, 4)
 CartesianIndex(10, 4)
 CartesianIndex(1, 5)
 CartesianIndex(2, 5)
 CartesianIndex(3, 5)
 CartesianIndex(5, 5)
 CartesianIndex(7, 5)
 CartesianIndex(10, 5)

In [136]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])
P = union(intersect(A, B), intersect(A, C), intersect(B, C))
println(P)

Set([0, 4, 7, 9, 3, 1])


In [138]:
# Пример 1: множество строк
set1 = Set(["cherry", "banana", "melon"])
set2 = Set(["banana", "cherry", "data"])
intersection = intersect(set1, set2)
println(intersection)

Set(["cherry", "banana"])


In [140]:
# Пример 2: множество чисел
set3 = Set([10, 20, 30])
set4 = Set([20, 40, 50])
difference = setdiff(set3, set4)
println(difference)

Set([10, 30])


In [144]:
N = 35
array1 = collect(1:N)
println(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]


In [146]:
array2 = collect(N:-1:1)
println(array2)

[35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [148]:
array3 = vcat(collect(1:N), collect(N-1:-1:1))
println(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [150]:
tmp = [4, 6, 3]
println(tmp)

[4, 6, 3]


In [152]:
array4 = fill(tmp[1], 10)
println(array4)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [156]:
array5 = repeat(tmp, 10)
println(array5)

[4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]


In [158]:
array6 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))
println(array6)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [160]:
array7 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))
println(array7)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [162]:
tmp = [4, 6, 3]

result_array = [2^tmp[i] for i in 1:3]
result_array = vcat(result_array, repeat([2^tmp[3]], 4))

result_string = join(result_array, "")
count_6 = count(x -> x == '6', result_string)

println("Результирующий массив: ", result_array)
println("Количество цифры 6: ", count_6)

Результирующий массив: [16, 64, 8, 8, 8, 8, 8]
Количество цифры 6: 2


In [166]:
using Statistics

x = 3:0.1:6
y = [exp(x) * cos(x) for x in x]

println("Среднее значение y: ", mean(y))

Среднее значение y: 53.11374594642971


In [168]:
xi = collect(3:3:36) * 0.1
yj = collect(1:3:34) * 0.2
vectorll = [(x, y) for x in xi, y in yj]
println(vectorll)

[(0.30000000000000004, 0.2) (0.30000000000000004, 0.8) (0.30000000000000004, 1.4000000000000001) (0.30000000000000004, 2.0) (0.30000000000000004, 2.6) (0.30000000000000004, 3.2) (0.30000000000000004, 3.8000000000000003) (0.30000000000000004, 4.4) (0.30000000000000004, 5.0) (0.30000000000000004, 5.6000000000000005) (0.30000000000000004, 6.2) (0.30000000000000004, 6.800000000000001); (0.6000000000000001, 0.2) (0.6000000000000001, 0.8) (0.6000000000000001, 1.4000000000000001) (0.6000000000000001, 2.0) (0.6000000000000001, 2.6) (0.6000000000000001, 3.2) (0.6000000000000001, 3.8000000000000003) (0.6000000000000001, 4.4) (0.6000000000000001, 5.0) (0.6000000000000001, 5.6000000000000005) (0.6000000000000001, 6.2) (0.6000000000000001, 6.800000000000001); (0.9, 0.2) (0.9, 0.8) (0.9, 1.4000000000000001) (0.9, 2.0) (0.9, 2.6) (0.9, 3.2) (0.9, 3.8000000000000003) (0.9, 4.4) (0.9, 5.0) (0.9, 5.6000000000000005) (0.9, 6.2) (0.9, 6.800000000000001); (1.2000000000000002, 0.2) (1.2000000000000002, 0.8)

In [172]:
M = 25
vector12 = [2^i / i for i in 1:M]
println(vector12)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


In [185]:
N = 30
vector13 = ["fn$i" for i in 1:N]

println(vector13)

["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


In [189]:
using Random

x = rand(0:999, 250)
y = rand(0:999, 250)

filtered_y = y[y .> 600]
println("Элементы y > 600", filtered_y)

corresponding_x = x[findall(y .> 600)]
println("Соответствующие x: ", corresponding_x)

unique_x = unique(x)
println("Уникальные элементы x:", unique_x)

Элементы y > 600[806, 868, 990, 687, 853, 646, 870, 842, 774, 722, 874, 863, 809, 886, 793, 825, 695, 956, 679, 779, 650, 898, 803, 869, 817, 819, 964, 631, 836, 635, 845, 855, 801, 727, 935, 728, 645, 940, 918, 807, 674, 743, 750, 615, 735, 778, 762, 752, 863, 863, 718, 952, 735, 687, 826, 636, 973, 681, 969, 810, 706, 662, 833, 882, 796, 607, 909, 787, 777, 908, 827, 632, 783, 851, 794, 875, 989, 661, 813, 659, 939, 887, 642, 833, 930, 926, 936, 920, 619, 723, 660, 603, 723]
Соответствующие x: [524, 717, 191, 106, 181, 353, 193, 303, 968, 751, 375, 110, 588, 335, 213, 703, 570, 368, 740, 27, 22, 52, 383, 7, 129, 638, 962, 572, 933, 769, 586, 398, 870, 559, 372, 273, 627, 816, 513, 320, 370, 316, 415, 611, 266, 395, 700, 313, 83, 335, 890, 725, 451, 991, 6, 101, 798, 315, 314, 892, 124, 470, 456, 32, 175, 434, 675, 74, 46, 109, 232, 548, 876, 903, 296, 613, 21, 742, 305, 141, 926, 550, 814, 862, 233, 382, 148, 823, 435, 485, 774, 542, 100]
Уникальные элементы x:[524, 717, 597, 667, 73

In [191]:
squares = [i^2 for i in 1:100]
println(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


In [202]:
using Primes

myprimes = primes(1000)

println("89-е наименьшее простое число: ", myprimes[89])
println("Срез: ", myprimes[89:99])

89-е наименьшее простое число: 461
Срез: [461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]


In [212]:
sum1 = sum(i^3 + 4*i^2 for i in 10:100)
println("Результат: ", sum1)

Результат: 26852735


In [214]:
sum2 = sum((2^i / i + 3^i / i^2) for i in 1:25)
println(sum2)

2.1291704368143802e9


In [216]:
sum3 = sum(prod(2:2n) / prod(3:2n+1) for n in 1:19)
println(sum3)

12.84175745993532
